# Generated by Django 4.0.1 on 2022-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('active_case', models.IntegerField()),
                ('new_infected', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('decreased', models.IntegerField()),
                ('new_decreased', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='india',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('total_death', models.IntegerField()),
                ('total_recovery', models.IntegerField()),
                ('total_newcase', models.IntegerField()),
                ('total_positive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='infected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total_infected', models.IntegerField()),
                ('new_infected', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='recover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('recovered_case', models.IntegerField()),
                ('new_recovered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('dose_1', models.IntegerField()),
                ('dose_2', models.IntegerField()),
            ],
        ),
    ]
