# Generated by Django 3.2.9 on 2022-01-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modify',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
